name: "Merge"

on:
  push:
    branches:
      - "master"

permissions: {}

jobs:
  release:
    name: "Merge"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4.1.0"
      - name: "Semantic Release"
        uses: "cycjimmy/semantic-release-action@v4"
        with:
          semantic_version: 23.0.2